title: ProductRecommendationCollection
allOf:
  - type: object
    properties:
      data:
        type: array
        items:
          $ref: '../models/ProductRecommendation.yaml'
  - $ref: '../../global/models/Pagination.yaml'
